---

webservers:
  hosts:
    local-docker:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_ssh_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    nginx-proxy-nyc2-01:
      ansible_host: 159.203.152.22

dev:
  hosts:
    local-docker

production:
  hosts:
    nginx-proxy-nyc2-01
