---

webservers:
  hosts:
    localhost:
      ansible_port: 2222
      ansible_ssh_args: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    reverse_proxy:
      ansible_host: 159.203.152.22

dev:
  hosts:
    localhost

production:
  hosts:
    reverse_proxy
