- hosts: webservers
  become: yes

  tasks:
  #   - name: Delete all files in sites-enabled
  #     file:
  #       path: "/etc/nginx/sites-enabled/*"
  #       state: absent

    - name: Nginx sites-available
      template:
        src: "{{ item }}"
        dest: "/etc/nginx/sites-available/{{ item | basename }}"
        mode: 644
      with_fileglob:
        - "templates/nginx/sites-available/*"

    - name: Create virtual host files for placeholder domains
      template:
        src: templates/nginx/virtual-host.conf.j2
        dest: "/etc/nginx/sites-available/{{ item.name }}"
        mode: "0644"
      loop: "{{ placeholders + www_data }}"
      when: site is not defined or site == item.name

    - name: Create directory path
      file:
        path: "/var/www/{{ item.name }}"
        state: directory
        mode: "0755"
      loop: "{{ placeholders + www_data }}"
      when: site is not defined or site == item.name

    - name: Clone www repositories
      git:
        repo: "{{ item.repo_url }}{{ item.repo_user }}/{{ item.repo_name }}.git"
        dest: "{{ clone_dir }}/{{ item.repo_name }}"
        clone: yes
        update: yes
      loop: "{{ www_data }}"
      when: (site is not defined or site == item.name) and item.repo_url is defined
      delegate_to: localhost
      become: no

    - name: Copy www data to webserver
      synchronize:
        src: "{{ item.local_path if item.local_path is defined else clone_dir + '/' + item.repo_name + '/' + item.www_folder }}/"
        dest: "/var/www/{{ item.name }}"
        delete: yes
      loop: "{{ www_data }}"
      when: site is not defined or site == item.name

    - name: Set www directory ownership
      file:
        path: "/var/www/{{ item.name }}"
        owner: root
        group: www-data
        recurse: yes
      loop: "{{ www_data }}"
      when: site is not defined or site == item.name

    - name: Set www directory permissions
      shell: |
        find /var/www/{{ item.name }} -type d -exec chmod 755 {} \;
        find /var/www/{{ item.name }} -type f -exec chmod 644 {} \;
      loop: "{{ www_data }}"
      when: site is not defined or site == item.name

    - name: Copy index.html to each domain directory
      template:
        src: templates/nginx/index.html.j2
        dest: "/var/www/{{ item.name }}/index.html"
        mode: "0644"
        group: www-data
      loop: "{{ placeholders }}"
      when: site is not defined or site == item.name

    - name: Create symlinks to enable sites
      file:
        src: "/etc/nginx/sites-available/{{ item.name }}"
        dest: "/etc/nginx/sites-enabled/{{ item.name }}"
        state: link
      loop: "{{ sites_enabled }}"

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_config_test
      failed_when: nginx_config_test.rc != 0
      notify:
        - reload nginx

  handlers:
    - name: reload nginx
      command: nginx -s reload
